# Generated by Django 5.1.6 on 2025-02-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='package_name',
        ),
        migrations.AddField(
            model_name='app',
            name='app_link',
            field=models.URLField(default='/', max_length=300),
        ),
        migrations.AddField(
            model_name='app',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
