# Generated by Django 5.1.6 on 2025-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_task_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
